apps:
  - name: imgx-nitro
    script: ./server/index.mjs
    interpreter: node
    exec_mode: fork
    env:
      PORT: 5777
  - name: imgx-ipx
    interpreter: bun
    script: bun
    args: ["x", "ipx", "serve", "--dir", "./public"]
    exec_mode: fork
    env:
      PORT: 5778
